[project]
name = "personal-assistant"
version = "0.1.0"
description = "Take your personal assistant"
readme = "README.md"
requires-python = ">=3.14"
authors = [
    { name = "Ihor M.", email = "mukovoz.igor@gmail.com" },
    { name = "Oleksii", email = "incretiblealex@gmail.com" },
    { name = "Myroslava", email = "myroslava.hnatiuk@ukr.net" },
    { name = "", email = "" },
]
dependencies = [
    "pydantic[email]>=2.13.4",
]
